### ISSUE TITLE
Counters in the README are slightly off?

### ISSUE THREAD

**Issue by Follpvosten** [H2CO3/avocado#9]
The "fuck counter" and the "goto counter" (does that one even make sense in Rust?) both show 1, but the only result is their entry in the README...
And the "unsafe counter" shows three, but the results are (again) the counter in the README, and then the `#![deny(...)]` entries which should make it impossible to have unsafe code...

I don't know if this is intentional, but it sounds like the counters don't really make sense. Just wanted to let you know :)

**Comment by H2CO3** [comment]
Hey there!

> both show 1, but the only result is their entry in the README...

That's right, apparently GitHub doesn't restrict these counters to source code. I didn't write the code for the counters. 😛 

> And the "unsafe counter" shows three, but the results are (again) the counter in the README, and then the #![deny(...)] entries which should make it impossible to have unsafe code...

Not quite, that would be `#![forbid(…)]`. `#![deny(…)]` can still be overridden locally with `#[allow(…)]`. It's not like I'd *like* to have to allow any unsafe code in this crate, but better safe than sorry.

**Comment by Follpvosten** [comment]
Hello!

Alright, good to know. If there's no problem with the counters being incorrect, you can just close the issue :)
I just wanted to point it out in case you didn't know. Removing the Goto counter might still be worth a thought tho, unless you plan on adding some C code to the crate at some point.
